<a href="https://colab.research.google.com/github/Ayiekoo/3D-numpy-plots/blob/main/Tensorflow_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
ximport os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf


In [ ]:
# Initialization of Tensors
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [ ]:
y = tf.constant([[1,2,3], [4,5,6]])
print(y)
# This code prints a 2 by 3 tensor.
# Two rows, each containing 3 columns

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
# We can obtain a 3 by 3 matrix of values of 1
d = tf.ones((3, 3))
print(d)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
l = tf.zeros((2, 3))
print(l)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [ ]:
f = tf.eye(3)
print(f)

# Prints 1 in the diagonal, and 0 everywhere else

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
t = tf.random.normal((3, 3), mean=0, stddev=1)
print(t)


tf.Tensor(
[[-0.22767624 -0.10118385  0.93934506]
 [-0.47384208  1.5704818  -0.62961817]
 [-1.1830813  -0.43404275  0.4437856 ]], shape=(3, 3), dtype=float32)


In [ ]:
m = tf.random.uniform((1, 3), minval=0, maxval=1)
print(m)

tf.Tensor([[0.24358404 0.12838936 0.10176563]], shape=(1, 3), dtype=float32)


In [ ]:
# Something similar to the python range function

s = tf.range(start=1, limit=10, delta=2)
print(s)

s = tf.cast(s, dtype=tf.float64)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


# **Mathematical operations**

In [ ]:
# Addition
b = tf.constant([1, 2, 3])
a = tf.constant([7, 8, 9])

c = tf.add(b, a)
print(c)

tf.Tensor([ 8 10 12], shape=(3,), dtype=int32)


In [ ]:
c = tf.multiply(b, a)
print(c)

tf.Tensor([ 7 16 27], shape=(3,), dtype=int32)


In [ ]:
c = tf.divide(b, a)
print(c)

tf.Tensor([0.14285714 0.25       0.33333333], shape=(3,), dtype=float64)


In [ ]:
c = tf.tensordot(b, a, axes=1)
print(c)

tf.Tensor(50, shape=(), dtype=int32)


In [ ]:
c = tf.reduce_sum(b*a, axis=0)
print(c)

tf.Tensor(50, shape=(), dtype=int32)


In [ ]:
c = b ** 5
print(c)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


# **Matrix** **multiplication**



In [ ]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))
z = tf.matmul(x, y)

print(z)

tf.Tensor(
[[ 0.43675256 -2.4643993  -1.2576458  -0.22530426]
 [ 0.2098796   0.9244318  -1.2070849  -2.0220487 ]], shape=(2, 4), dtype=float32)


# **Indexing** **a** **tensor**

In [ ]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:]) # Excludes the first index

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [ ]:
print(x[1: 3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [ ]:
print(x[::2]) # Skips values after one value in the list

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [ ]:
# We can print in reverse
print(x[::-1])

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


# **Reshaping** **a** **matrix**

In [ ]:
X =tf.range(9)
print(X)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [ ]:
X =tf.reshape(X, (3, 3))
print(X)

# Reshapes the matrix to a 3 by 3

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [ ]:
X = tf.transpose(X, perm=[1, 0])
print(X)

# Flips and interchanges the columns and rows of the matrix.

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
